### ISSUE TITLE
关于pytorch1.8+cuda11.1的问题

### ISSUE THREAD

**Issue by hjq052070** [WZMIAOMIAO/deep-learning-for-image-processing#239]
由于我的显卡是3090，所以最初安装的是pytorch1.7.1+cuda11.0，但是会出现loss为nan的情况。看了b站评论说是可能为cuda11的问题，cuda10.x就没有问题了。我在网上查了查，说是pytorch1.7+cuda11兼容性不佳，而且nvidia官方建议30系列显卡使用cuda11.1？我就试了试，装了pytorch1.8+cuda11.1，结果别说nan了，直接就运行不了：
Using 2 dataloader workers
Traceback (most recent call last):
  File "/hdd/HJQ/faster_rcnn/train_res50_fpn.py", line 185, in <module>
    main(args)
  File "/hdd/HJQ/faster_rcnn/train_res50_fpn.py", line 106, in main
    print_freq=1, warmup=True)
  File "/hdd/HJQ/faster_rcnn/train_utils/train_eval_utils.py", line 33, in train_one_epoch
    loss_dict = model(images, targets)
  File "/home/hjq/anaconda3/envs/pytorch1.8/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/hdd/HJQ/faster_rcnn/network_files/faster_rcnn_framework.py", line 94, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/hjq/anaconda3/envs/pytorch1.8/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/hdd/HJQ/faster_rcnn/network_files/rpn_function.py", line 629, in forward
    objectness, pred_bbox_deltas, labels, regression_targets
  File "/hdd/HJQ/faster_rcnn/network_files/rpn_function.py", line 537, in compute_loss
    sampled_pos_inds, sampled_neg_inds = self.fg_bg_sampler(labels)
  File "/hdd/HJQ/faster_rcnn/network_files/det_utils.py", line 65, in __call__
    perm2 = torch.randperm(negative.numel(), device=negative.device)[:num_neg]
RuntimeError: radix_sort: failed on 1st step: cudaErrorInvalidDevice: invalid device ordinal

Process finished with exit code 1

或许有没有小伙伴遇到这个问题并解决，或者有没有人在3090显卡上顺利运行啊？3090只支持cuda11.x，枯了。。。

**Comment by WZMIAOMIAO** [comment]
pytorch1.8+cuda11.1有bug，官方问题。可以尝试night版（1.9）
