### ISSUE TITLE
CUDA version

### ISSUE THREAD

**Issue by zmz125** [WZMIAOMIAO/deep-learning-for-image-processing#240]
**System information**
* Have I written custom code: No
* OS Platform(e.g., window10 or Linux Ubuntu 16.04): Ubuntu 16.04.6 LTS
* Python version: 3.7.10
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3): Pytorch 1.6.0
* Use GPU or not: No
* CUDA/cuDNN version(if you use GPU):  CUDA Version 10.1.243
* The network you trained(e.g., Resnet34 network): pytorch_object_detection/faster_rcnn/train_res50_fpn.py

**Describe the current behavior**
May I ask what version of CUDA is needed for this project?
Will CUDA 10.1 not work?

**Error info / logs**
AssertionError: 
The NVIDIA driver on your system is too old (found version 10010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

**Comment by WZMIAOMIAO** [comment]
NVIDIA Driver Version: >= 418.39
CUDA: 10.1

**Comment by zmz125** [comment]
![image](https://user-images.githubusercontent.com/64347292/116213906-c3556600-a778-11eb-8608-303889131018.png)
Why does this report an error?

**Comment by WZMIAOMIAO** [comment]
using this command to check your CUDA version:
```
 nvcc -V
```

maybe there's something wrong with the way you installed pytorch, the right way:
```
pip install torch==1.7.1+cu101 torchvision==0.8.2+cu101 -f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by zmz125** [comment]
非常感谢，我重装了PyTorch应该是可以了
一开始nvcc提示找不到该命令，然后我又添加了环境变量/usr/local/cuda-10.1/bin
可以用了，使用nvcc -V显示
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

但是再次使用GPU运行，提示以下问题，是不是两个显卡的环境变量没有配置好？
python -m torch.distributed.launch --nproc_per_node=2 --use_env train_multi_GPU.py
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
| distributed init (rank 0): env://
Traceback (most recent call last):
  File "train_multi_GPU.py", line 248, in <module>
    main(args)
  File "train_multi_GPU.py", line 39, in main
    init_distributed_mode(args)
  File "/root/workPlace/zmz/LJ/bilibili_wz/pytorch_object_detection/faster_rcnn/train_utils/distributed_utils.py", line 320, in init_distributed_mode
    world_size=args.world_size, rank=args.rank)
  File "/home/miniconda3/envs/pyt/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 436, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/miniconda3/envs/pyt/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 179, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
RuntimeError: Address already in use
| distributed init (rank 1): env://
Traceback (most recent call last):
  File "/home/miniconda3/envs/pyt/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/miniconda3/envs/pyt/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/miniconda3/envs/pyt/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/miniconda3/envs/pyt/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/miniconda3/envs/pyt/bin/python', '-u', 'train_multi_GPU.py']' returned non-zero exit status 1.

**Comment by WZMIAOMIAO** [comment]
```RuntimeError: Address already in use```
提示端口地址已被占用，你用```nvidia -smi```检查是否有任务在占用GPU资源没有释放，确保两个GPU都没有在使用的情况下，再启动。还有，你这两个GPU不是同型号的，使用GPU并行可能会有问题。可能直接使用单块V100更快。

**Comment by zmz125** [comment]
厉害厉害，好像是这个原因，我又换了台服务器，没有任务在运行，但是又提示了新的错误
`*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
| distributed init (rank 1): env://
| distributed init (rank 2): env://
| distributed init (rank 0): env://
Namespace(aspect_ratio_group_factor=3, batch_size=4, data_path='./', device='cuda', dist_backend='nccl', dist_url='env://', distributed=True, epochs=20, gpu=0, lr=0.02, lr_gamma=0.1, lr_step_size=8, lr_steps=[7, 12], momentum=0.9, num_classes=20, output_dir='./multi_train', print_freq=20, rank=0, resume='', start_epoch=0, test_only=False, weight_decay=0.0001, workers=4, world_size=3)
Loading data
Creating data loaders
Using [0, 0.5, 0.6299605249474366, 0.7937005259840997, 1.0, 1.2599210498948732, 1.5874010519681994, 2.0, inf] as bins for aspect ratio quantization
Count of instances per bin: [   5   25  929  117  260 4198  135   48]
Creating model
Start training
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "/opt/conda/envs/pyt/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/envs/pyt/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 321, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_18895_3602745834>
Traceback (most recent call last):
  File "/opt/conda/envs/pyt/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/envs/pyt/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 321, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_18900_416030506>
Traceback (most recent call last):
  File "/opt/conda/envs/pyt/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/envs/pyt/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 321, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_18911_2398138023>
Traceback (most recent call last):
  File "/opt/conda/envs/pyt/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/envs/pyt/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 321, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_18921_758570246>
Traceback (most recent call last):
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/conda/envs/pyt/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/opt/conda/envs/pyt/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/opt/conda/envs/pyt/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/opt/conda/envs/pyt/lib/python3.7/multiprocessing/connection.py", line 921, in wait
    ready = selector.select(timeout)
  File "/opt/conda/envs/pyt/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 18897) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_multi_GPU.py", line 248, in <module>
    main(args)
  File "train_multi_GPU.py", line 136, in main
    epoch, args.print_freq, warmup=True)
  File "/root/zmz/faster_rcnn/train_utils/train_eval_utils.py", line 28, in train_one_epoch
    for i, [images, targets] in enumerate(metric_logger.log_every(data_loader, print_freq, header)):
  File "/root/zmz/faster_rcnn/train_utils/distributed_utils.py", line 204, in log_every
    for obj in iterable:
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1034, in _get_data
    success, data = self._try_get_data()
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 885, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 18894, 18897) exited unexpectedly
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "/opt/conda/envs/pyt/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/envs/pyt/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 321, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_18895_2885352318>
Traceback (most recent call last):
  File "/opt/conda/envs/pyt/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/envs/pyt/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 321, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_18911_581034045>
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/conda/envs/pyt/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/opt/conda/envs/pyt/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/opt/conda/envs/pyt/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/opt/conda/envs/pyt/lib/python3.7/multiprocessing/connection.py", line 921, in wait
    ready = selector.select(timeout)
  File "/opt/conda/envs/pyt/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 18900) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_multi_GPU.py", line 248, in <module>
    main(args)
  File "train_multi_GPU.py", line 136, in main
    epoch, args.print_freq, warmup=True)
  File "/root/zmz/faster_rcnn/train_utils/train_eval_utils.py", line 28, in train_one_epoch
    for i, [images, targets] in enumerate(metric_logger.log_every(data_loader, print_freq, header)):
  File "/root/zmz/faster_rcnn/train_utils/distributed_utils.py", line 204, in log_every
    for obj in iterable:
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1034, in _get_data
    success, data = self._try_get_data()
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 885, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 18900) exited unexpectedly
Traceback (most recent call last):
  File "/opt/conda/envs/pyt/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/pyt/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/envs/pyt/bin/python', '-u', 'train_multi_GPU.py']' returned non-zero exit status 1.
`

**Comment by WZMIAOMIAO** [comment]
```ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).```
应该是你硬件资源受限的原因，可以尝试以下两个方法：
1）把dataloader的num_worker设置为0
2）减小batch_size

我在网上找的博文，不知道对你有没有用：https://blog.csdn.net/u013823233/article/details/101209718

**Comment by zmz125** [comment]
对对对，感谢感谢非常感谢，就是这个问题，num_worker改成0可以训练了
但是又出现了新的问题，哭，麻烦您了
训练完一个Epoch，在回溯时出现了问题，请问是程序的问题吗？怎么解决

Epoch: [0] Total time: 0:08:22 (0.3517 s / it)
creating index...
index created!
Traceback (most recent call last):
  File "train_multi_GPU.py", line 248, in <module>
    main(args)
  File "train_multi_GPU.py", line 144, in main
    coco_info = utils.evaluate(model, data_loader_test, device=device)
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/root/zmz/faster_rcnn/train_utils/train_eval_utils.py", line 77, in evaluate
    coco_evaluator = CocoEvaluator(coco, iou_types)
  File "/root/zmz/faster_rcnn/train_utils/coco_eval.py", line 24, in __init__
    self.coco_eval[iou_type] = COCOeval(coco_gt, iouType=iou_type)
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 527, in __init__
    self.setDetParams()
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 6, in linspace
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/numpy/core/function_base.py", line 120, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/opt/conda/envs/pyt/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/pyt/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/opt/conda/envs/pyt/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/envs/pyt/bin/python', '-u', 'train_multi_GPU.py']' returned non-zero exit status 1.

**Comment by WZMIAOMIAO** [comment]
在pycocotools库中找到cocoeval.py文件，大概507行。 修改self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)为self.iouThrs = np.linspace(.5, 0.95, int(np.round((0.95 - .5) / .05) + 1), endpoint=True)修改self.recThrs = np.linspace(.0, 1.00, np.round((1.00 - .0) / .01) + 1, endpoint=True)为self.recThrs = np.linspace(.0, 1.00, int(np.round((1.00 - .0) / .01) + 1), endpoint=True)
