### ISSUE TITLE
用PascalVoc数据集运行train.py一个epoch以后无法计算iou

### ISSUE THREAD

**Issue by HEFORSHEe** [WZMIAOMIAO/deep-learning-for-image-processing#245]
Traceback (most recent call last):
  File "train_mobilenetv2.py", line 197, in <module>
    main()
  File "train_mobilenetv2.py", line 118, in main
    coco_info = utils.evaluate(model, val_data_set_loader, device=device)
  File "/home/hyj/anaconda3/envs/torch/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/hyj/pytorch_object_detection/faster_rcnn/train_utils/train_eval_utils.py", line 75, in evaluate
    coco = get_coco_api_from_dataset(data_loader.dataset)
  File "/home/hyj/pytorch_object_detection/faster_rcnn/train_utils/coco_utils.py", line 54, in get_coco_api_from_dataset
    return convert_to_coco_api(dataset)
  File "/home/hyj/pytorch_object_detection/faster_rcnn/train_utils/coco_utils.py", line 15, in convert_to_coco_api
    hw, targets = ds.coco_index(img_idx)
AttributeError: 'VOC2012DataSet' object has no attribute 'coco_index'

**Comment by WZMIAOMIAO** [comment]
用最新代码

**Comment by HEFORSHEe** [comment]
使用了最新代码 一个epoch以后还是出现类似问题 请问是什么原因
  File "/home/hyj/pytorch_object_detection/faster_rcnn/train_mobilenetv2.py", line 117, in main
    coco_info = utils.evaluate(model, val_data_set_loader, device=device)
  File "/home/hyj/anaconda3/envs/torch/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/hyj/pytorch_object_detection/faster_rcnn/train_utils/train_eval_utils.py", line 75, in evaluate
    coco = get_coco_api_from_dataset(data_loader.dataset)
  File "/home/hyj/pytorch_object_detection/faster_rcnn/train_utils/coco_utils.py", line 54, in get_coco_api_from_dataset
    return convert_to_coco_api(dataset)
  File "/home/hyj/pytorch_object_detection/faster_rcnn/train_utils/coco_utils.py", line 15, in convert_to_coco_api
    hw, targets = ds.coco_index(img_idx)
  File "/home/hyj/pytorch_object_detection/faster_rcnn/my_dataset.py", line 158, in coco_index
    labels.append(self.class_dict[obj["name"]])
KeyError: 'd'

**Comment by WZMIAOMIAO** [comment]
也明显不是一个问题，
```
labels.append(self.class_dict[obj["name"]])
KeyError: 'd'
```
提示的很清楚，标签文件里没有```d```这个类别

**Comment by HEFORSHEe** [comment]
解决了  感谢!
