### ISSUE TITLE
YOLOV3_spp运行问题

### ISSUE THREAD

**Issue by dudiaoxifenglie** [WZMIAOMIAO/deep-learning-for-image-processing#250]
D:\Anaconda\envs\py36\python.exe C:/Users/FuGuodong/Desktop/pytorch_Study/Study_Video/yolov3_spp/train.py
Namespace(batch_size=4, cache_images=False, cfg='cfg/my_yolov3.cfg', data='data/my_data.data', device='cuda:0', epochs=30, freeze_layers=False, hyp='cfg/hyp.yaml', img_size=512, multi_scale=True, name='', notest=False, rect=False, savebest=False, single_cls=False, weights='weights/yolov3-spp-ultralytics-512.pt')
Start Tensorboard with "tensorboard --logdir=runs", view at http://localhost:6006/
Using cuda device training.
Using multi_scale training, image range[320, 736]
Model Summary: 225 layers, 6.26756e+07 parameters, 6.26756e+07 gradients
Caching labels (5717 found, 0 missing, 0 empty, 0 duplicate, for 5717 images): 100%|██████████| 5717/5717 [00:02<00:00, 2101.88it/s]
Saving labels to my_yolo_dataset\train\labels.norect.npy for faster future loading
D:\Anaconda\envs\py36\lib\site-packages\numpy\core\_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
Caching labels (5823 found, 0 missing, 0 empty, 0 duplicate, for 5823 images): 100%|██████████| 5823/5823 [00:02<00:00, 2104.71it/s]
Saving labels to my_yolo_dataset\val\labels.rect.npy for faster future loading
C:\Users\FuGuodong\Desktop\pytorch_Study\Study_Video\yolov3_spp\build_utils\layers.py:66: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if nx == na:  # same shape 如果channel相同，直接相加
C:\Users\FuGuodong\Desktop\pytorch_Study\Study_Video\yolov3_spp\models.py:166: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if (self.nx, self.ny) != (nx, ny) or self.grid is None:  # fix no grid bug
C:\Users\FuGuodong\Desktop\pytorch_Study\Study_Video\yolov3_spp\models.py:148: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  self.ng = torch.tensor(ng, dtype=torch.float)
C:\Users\FuGuodong\Desktop\pytorch_Study\Study_Video\yolov3_spp\models.py:148: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  self.ng = torch.tensor(ng, dtype=torch.float)
Traceback (most recent call last):
  File "C:/Users/FuGuodong/Desktop/pytorch_Study/Study_Video/yolov3_spp/train.py", line 292, in <module>
    train(hyp)
  File "C:/Users/FuGuodong/Desktop/pytorch_Study/Study_Video/yolov3_spp/train.py", line 187, in train
    w.add_graph(model.cpu(),input_data)
  File "D:\Anaconda\envs\py36\lib\site-packages\torch\utils\tensorboard\writer.py", line 714, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose))
  File "D:\Anaconda\envs\py36\lib\site-packages\torch\utils\tensorboard\_pytorch_graph.py", line 285, in graph
    trace = torch.jit.trace(model, args)
  File "D:\Anaconda\envs\py36\lib\site-packages\torch\jit\__init__.py", line 955, in trace
    check_tolerance, strict, _force_outplace, _module_class)
  File "D:\Anaconda\envs\py36\lib\site-packages\torch\jit\__init__.py", line 1119, in trace_module
    check_tolerance, strict, _force_outplace, True, _module_class)
  File "D:\Anaconda\envs\py36\lib\site-packages\torch\autograd\grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "D:\Anaconda\envs\py36\lib\site-packages\torch\jit\__init__.py", line 742, in _check_trace
    raise TracingCheckError(*diag_info)
torch.jit.TracingCheckError: Tracing failed sanity checks!
ERROR: Graphs differed across invocations!
	Graph diff:
		  graph(%self.1 : __torch__.models.Darknet,
		        %input.1 : Tensor):
		    %2 : __torch__.torch.nn.modules.container.ModuleList = prim::GetAttr[name="module_list"](%self.1)
		    %3 : __torch__.models.YOLOLayer = prim::GetAttr[name="113"](%2)
		    %4 : __torch__.torch.nn.modules.container.ModuleList = prim::GetAttr[name="module_list"](%self.1)
		    %5 : __torch__.torch.nn.modules.container.Sequential = prim::GetAttr[name="112"](%4)
		    %6 : __torch__.torch.nn.modules.container.ModuleList = prim::GetAttr[name="module_list"](%self.1)
。。。

**Comment by dudiaoxifenglie** [comment]
实在不知道问题出在哪里了
