### ISSUE TITLE
使用VOC2007

### ISSUE THREAD

**Issue by MaLiXiaoGuo** [WZMIAOMIAO/deep-learning-for-image-processing#253]
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mty/workspace/pytorch_object_detection/retinaNet/train_utils/__init__.py", line 3, in <module>
    from .coco_utils import get_coco_api_from_dataset
  File "/home/mty/workspace/pytorch_object_detection/retinaNet/train_utils/coco_utils.py", line 4, in <module>
    from pycocotools.coco import COCO
  File "/home/mty/anaconda3/envs/dalaode/lib/python3.7/site-packages/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/mty/anaconda3/envs/dalaode/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by WZMIAOMIAO** [comment]
请先按照问题模板把问题全部回答了。
