### ISSUE TITLE
faster_rcnn中train_mobilenet.py训练完一个epoch就会报错

### ISSUE THREAD

**Issue by QQR1** [WZMIAOMIAO/deep-learning-for-image-processing#31]
**System information**

* OS Platform(e.g., window10 ):window10
* Python version:3.7
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3):Pytorch1.5
* Use GPU or not:GPU
* CUDA/cuDNN version(if you use GPU):cuda10.1
* The network you trained(e.g., Resnet34 network):mobilenet

**Describe the current behavior**

**Error info / logs**
Traceback (most recent call last):
  File "E:\Anaconda\envs\PyTorch\Lib\site-packages\numpy\core\function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/FirstYearMaster/ObjectDetection/Faster RCNN/faster_rcnn/train_mobilenet.py", line 146, in <module>
    main()
  File "D:/FirstYearMaster/ObjectDetection/Faster RCNN/faster_rcnn/train_mobilenet.py", line 93, in main
    utils.evaluate(model, val_data_set_loader, device=device)
  File "E:\Anaconda\envs\PyTorch\Lib\site-packages\torch\autograd\grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "D:\FirstYearMaster\ObjectDetection\Faster RCNN\faster_rcnn\train_utils\train_eval_utils.py", line 70, in evaluate
    coco_evaluator = CocoEvaluator(coco, iou_types)
  File "D:\FirstYearMaster\ObjectDetection\Faster RCNN\faster_rcnn\train_utils\coco_eval.py", line 28, in __init__
    self.coco_eval[iou_type] = COCOeval(coco_gt, iouType=iou_type)
  File "E:\Anaconda\envs\PyTorch\Lib\site-packages\pycocotools\cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "E:\Anaconda\envs\PyTorch\Lib\site-packages\pycocotools\cocoeval.py", line 527, in __init__
    self.setDetParams()
  File "E:\Anaconda\envs\PyTorch\Lib\site-packages\pycocotools\cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 6, in linspace
  File "E:\Anaconda\envs\PyTorch\Lib\site-packages\numpy\core\function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

**Comment by WZMIAOMIAO** [comment]
是pycocotools的问题，这个问题只有在window环境下才会出现      
你import pycocotools.cocoeval      
然后进入cocoeval的507行左右：   
```
self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
self.recThrs = np.linspace(.0, 1.00, np.round((1.00 - .0) / .01) + 1, endpoint=True)
```

改为：    

```
# np.arange causes trouble.  the data point on arange is slightly larger than the true value
self.iouThrs = np.linspace(.5, 0.95, int(np.round((0.95 - .5) / .05)) + 1, endpoint=True)
self.recThrs = np.linspace(.0, 1.00, int(np.round((1.00 - .0) / .01)) + 1, endpoint=True)
```

**Comment by QQR1** [comment]
非常感谢! 问题解决了。




任秋霖
tjrenqiulin@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"WZMIAOMIAO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月2日(星期四) 晚上9:20
收件人:&nbsp;"WZMIAOMIAO/deep-learning-for-image-processing"<deep-learning-for-image-processing@noreply.github.com&gt;;
抄送:&nbsp;"天堂钟声"<1298345189@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [WZMIAOMIAO/deep-learning-for-image-processing] faster_rcnn中train_mobilenet.py训练完一个epoch就会报错 (#31)





 
是pycocotools的问题，这个问题只有在window环境下才会出现
 你import pycocotools.cocoeval
 然后进入cocoeval的507行左右：
 self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True) self.recThrs = np.linspace(.0, 1.00, np.round((1.00 - .0) / .01) + 1, endpoint=True)  
改为：
 # np.arange causes trouble.  the data point on arange is slightly larger than the true value self.iouThrs = np.linspace(.5, 0.95, int(np.round((0.95 - .5) / .05)) + 1, endpoint=True) self.recThrs = np.linspace(.0, 1.00, int(np.round((1.00 - .0) / .01)) + 1, endpoint=True)
