### ISSUE TITLE
MobileNetV2 训练报错

### ISSUE THREAD

**Issue by RazerTang** [WZMIAOMIAO/deep-learning-for-image-processing#314]
**System information**
* Have I written custom code: NO 
* OS Platform(e.g., window10 or Linux Ubuntu 16.04):  MacOS Big Sur
* Python version: 3.9.5
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3): Pytorch 1.9
* Use GPU or not: Not
* CUDA/cuDNN version(if you use GPU):
* The network you trained(e.g., Resnet34 network): MobileNetV2

**Describe the current behavior**

**Error info / logs**
<img width="1228" alt="截屏2021-07-04 下午11 37 17" src="https://user-images.githubusercontent.com/5905640/124391018-0572c900-dd21-11eb-8f31-c45432acb291.png">

**Comment by WZMIAOMIAO** [comment]
没用macos测试过，看错误提示感觉可能是dataloder的问题，你把num_work设置成0试下。

**Comment by RazerTang** [comment]
> num_work
还是报错

using cpu device.
Using 0 dataloader workers every process
using 3306 images for training, 364 images for validation.
  0%|                                                         | 0/207 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/sunny/Documents/deep-learning-for-image-processing/pytorch_classification/Test6_mobilenet/train.py", line 144, in <module>
    main()
  File "/Users/sunny/Documents/deep-learning-for-image-processing/pytorch_classification/Test6_mobilenet/train.py", line 103, in main
    for step, data in enumerate(train_bar):
  File "/usr/local/lib/python3.9/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 234, in __getitem__
    sample = self.transform(sample)
  File "/usr/local/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/usr/local/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 97, in __call__
    return F.to_tensor(pic)
  File "/usr/local/lib/python3.9/site-packages/torchvision/transforms/functional.py", line 129, in to_tensor
    np.array(pic, mode_to_nptype.get(pic.mode, np.uint8), copy=True)
TypeError: __array__() takes 1 positional argument but 2 were given

**Comment by WZMIAOMIAO** [comment]
```
np.array(pic, mode_to_nptype.get(pic.mode, np.uint8), copy=True)
TypeError: array() takes 1 positional argument but 2 were given
```
好像是numpy的问题，你重装成1.17.0版本试下。

**Comment by CIown** [comment]
我也是这个错误

**Comment by RazerTang** [comment]
> ```
> np.array(pic, mode_to_nptype.get(pic.mode, np.uint8), copy=True)
> TypeError: array() takes 1 positional argument but 2 were given
> ```
> 
> 好像是numpy的问题，你重装numpy成1.17.0版本试下。

macOS BigSur装不了1.17.0版本，最低降级到1.19.0版本，报错依旧 - -

**Comment by WZMIAOMIAO** [comment]
这样，你先检查下你的torch版本和torchvision的版本是否适配，torch1.9.0是和torchvision0.10.0匹配的。
如果torch版本和torchvision的版本是适配的但依然存在问题，就尝试降级到torch1.71以及对应的torchvision0.8.2。

**Comment by bamboopu** [comment]
> > ```
> > np.array(pic, mode_to_nptype.get(pic.mode, np.uint8), copy=True)
> > TypeError: array() takes 1 positional argument but 2 were given
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 好像是numpy的问题，你重装numpy成1.17.0版本试下。
> 
> macOS BigSur装不了1.17.0版本，最低降级到1.19.0版本，报错依旧 - -
> 还有没其它方法能绕过

应该不是mac不让装numpy吧，可能是py3.9不让装，可以新建py3.6的conda环境再试试。num_workers因为win和linux多进程的区别在win下需要设置成0，在OS下我不知道。

**Comment by WZMIAOMIAO** [comment]
刚刚b站上有个小伙伴说把Pillow降级到8.2.0就正常了，你可以试试

**Comment by CIown** [comment]
> ```
> np.array(pic, mode_to_nptype.get(pic.mode, np.uint8), copy=True)
> TypeError: array() takes 1 positional argument but 2 were given
> ```
> 
> 好像是numpy的问题，你重装numpy成1.17.0版本试下。

windows 装不了1.17.0 。Pillow降级到8.2.0就好了。

**Comment by RazerTang** [comment]
> 8.2.0

降级到8.2.0 后问题解决了 谢谢
