### ISSUE TITLE
TypeError: object of type 'int' has no len() 

### ISSUE THREAD

**Issue by ts19970816** [WZMIAOMIAO/deep-learning-for-image-processing#342]
/home/ts/anaconda3/bin/python3 /home/ts/project/deep-learning-for-image-processing-master/pytorch_object_detection/faster_rcnn/train_res50_fpn.py
Namespace(aspect_ratio_group_factor=3, batch_size=8, data_path='./', device='cuda:0', epochs=15, num_classes=5, output_dir='./save_weights', resume='', start_epoch=0)
Using cpu device training.
Using [0, 0.5, 0.6299605249474366, 0.7937005259840997, 1.0, 1.2599210498948732, 1.5874010519681994, 2.0, inf] as bins for aspect ratio quantization
Count of instances per bin: [1076]
Using 0 dataloader workers
Traceback (most recent call last):
  File "/home/ts/project/deep-learning-for-image-processing-master/pytorch_object_detection/faster_rcnn/train_res50_fpn.py", line 206, in <module>
    main(args)
  File "/home/ts/project/deep-learning-for-image-processing-master/pytorch_object_detection/faster_rcnn/train_res50_fpn.py", line 135, in main
    print_freq=50, warmup=True)
  File "/home/ts/project/deep-learning-for-image-processing-master/pytorch_object_detection/faster_rcnn/train_utils/train_eval_utils.py", line 24, in train_one_epoch
    print(len(data_loader))
  File "/home/ts/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 397, in __len__
    return len(self._index_sampler)
TypeError: object of type 'int' has no len()

**Comment by ts19970816** [comment]
How to solve this error

**Comment by WZMIAOMIAO** [comment]
请先按照问题模板把问题填清楚
