### ISSUE TITLE
RuntimeError: CUDA driver error: a PTX JIT compilation failed

### ISSUE THREAD

**Issue by YuanZhichao** [WZMIAOMIAO/deep-learning-for-image-processing#357]
**Ubuntu16.04**
**GPU RTX 2080Ti**
**python3.7，CUDA10.0， pytorch1.6.0**

* 运行python train_mobilenetv2.py报错：
> Traceback (most recent call last):
>   File "train_mobilenetv2.py", line 220, in <module>
>     main()
>   File "train_mobilenetv2.py", line 136, in main
>     device, epoch, print_freq=50, warmup=True)
>   File "/home/yuhang2019/ysrfast/train_utils/train_eval_utils.py", line 34, in train_one_epoch
>     loss_dict = model(images, targets)
>   File "/home/yuhang2019/anaconda3/envs/pytorch1.6/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/yuhang2019/ysrfast/network_files/faster_rcnn_framework.py", line 92, in forward
>     proposals, proposal_losses = self.rpn(images, features, targets)
>   File "/home/yuhang2019/anaconda3/envs/pytorch1.6/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/yuhang2019/ysrfast/network_files/rpn_function.py", line 641, in forward
>     regression_targets = self.box_coder.encode(matched_gt_boxes, anchors)
>   File "/home/yuhang2019/ysrfast/network_files/det_utils.py", line 174, in encode
>     targets = self.encode_single(reference_boxes, proposals)
>   File "/home/yuhang2019/ysrfast/network_files/det_utils.py", line 189, in encode_single
>     targets = encode_boxes(reference_boxes, proposals, weights)
>   File "/home/yuhang2019/anaconda3/envs/pytorch1.6/lib/python3.7/site-packages/torch/jit/__init__.py", line 1600, in wrapper
>     return compiled_fn(*args, **kwargs)
> RuntimeError: The following operation failed in the TorchScript interpreter.
> Traceback of TorchScript (most recent call last):
> RuntimeError: CUDA driver error: a PTX JIT compilation failed

请问是什么原因？

**Comment by WZMIAOMIAO** [comment]
首先不知道你GPU驱动是否正确，其次，pytorch1.6不支持CUDA10.0
