### ISSUE TITLE
RuntimeError: class '__torch__.network_files.image_list.ImageList' already defined.

### ISSUE THREAD

**Issue by XinChengHuNan** [WZMIAOMIAO/deep-learning-for-image-processing#37]
Reloaded modules: transforms
Traceback (most recent call last):

  File "/home2/cx/WeakDet/deep-learning-for-image-processing/pytorch_object_detection/faster_rcnn/train_res50_fpn.py", line 3, in <module>
    from network_files.faster_rcnn_framework import FasterRCNN, FastRCNNPredictor

  File "/home2/cx/WeakDet/deep-learning-for-image-processing/pytorch_object_detection/faster_rcnn/network_files/faster_rcnn_framework.py", line 4, in <module>
    from network_files.rpn_function import AnchorsGenerator, RPNHead, RegionProposalNetwork

  File "/home2/cx/WeakDet/deep-learning-for-image-processing/pytorch_object_detection/faster_rcnn/network_files/rpn_function.py", line 9, in <module>
    from network_files.image_list import ImageList

  File "/home2/cx/WeakDet/deep-learning-for-image-processing/pytorch_object_detection/faster_rcnn/network_files/image_list.py", line 7, in <module>
    class ImageList(object):

  File "/home/cx/anaconda3/envs/fcn_torch1.0/lib/python3.6/site-packages/torch/jit/__init__.py", line 1280, in script
    _compile_and_register_class(obj, _rcb, qualified_name)

  File "/home/cx/anaconda3/envs/fcn_torch1.0/lib/python3.6/site-packages/torch/jit/__init__.py", line 1108, in _compile_and_register_class
    _jit_script_class_compile(qualified_name, ast, rcb)

RuntimeError: class '__torch__.network_files.image_list.ImageList' already defined.

**Comment by super-wz** [comment]
are you using pytorch version 1.5.0 ? please read reademe firstly.

**Comment by XinChengHuNan** [comment]
> are you using pytorch version 1.5.0 ? please read reademe firstly.

thank you for response , yes, I am using 1.5.1. don't care about the envs, I install 1.5.1 for this program.
