### ISSUE TITLE
“FileNotFoundError: VOCdevkit dose not in path:'./'.”

### ISSUE THREAD

**Issue by TaoistPriestC** [WZMIAOMIAO/deep-learning-for-image-processing#447]
新手入门，哔站过来的，折腾两天配好环境，运行`python train_mobilenetv2.py`出现下列报错：
```
Using cuda device training.
Traceback (most recent call last):
  File "train_mobilenetv2.py", line 224, in <module>
    main()
  File "train_mobilenetv2.py", line 65, in main
    raise FileNotFoundError("VOCdevkit dose not in path:'{}'.".format(VOC_root))
FileNotFoundError: VOCdevkit dose not in path:'./'.
```
看到README里面注意事项“在使用训练脚本时，注意要将'--data-path'(VOC_root)设置为自己存放'VOCdevkit'文件夹所在的根目录”，直觉告诉我跟这有关，但是没太看懂引号里面这句话，不知道怎么操作…

然后我在`train_mobilenetv2.py`文件里面看到了下面这行代码，
```python
VOC_root = "./"  # VOCdevkit
```
我在想，这个报错是不是在说“VOCdevkit”根目录设置不对呢，假如我把根目录设为“./”，那么是不是要把“VOCdevkit”放在“./”目录之下。我比较小白，想问一下这个“VOCdevkit”到底是什么呢？又或者说，是我想多了，“VOCdevkit”就是一个自建的文件夹？

**Comment by WZMIAOMIAO** [comment]
你把pascal数据集下载下来后解压就是个```VOCdeckit```文件夹啊。
```./```代表当前项目所在根目录，你如果把```VOCdeckit```放在项目根目录就可以直接用。你如果是放在其他地方，就把读取数据的路径改成```VOCdeckit```文件夹所在的根目录。
```
VOCdevkit
    └── VOC2012
         ├── Annotations               所有的图像标注信息(XML文件)
         ├── ImageSets    
         │   ├── Action                人的行为动作图像信息
         │   ├── Layout                人的各个部位图像信息
         │   │
         │   ├── Main                  目标检测分类图像信息
         │   │     ├── train.txt       训练集(5717)
         │   │     ├── val.txt         验证集(5823)
         │   │     └── trainval.txt    训练集+验证集(11540)
         │   │
         │   └── Segmentation          目标分割图像信息
         │         ├── train.txt       训练集(1464)
         │         ├── val.txt         验证集(1449)
         │         └── trainval.txt    训练集+验证集(2913)
         │ 
         ├── JPEGImages                所有图像文件
         ├── SegmentationClass         语义分割png图（基于类别）
         └── SegmentationObject        实例分割png图（基于目标）

```
