### ISSUE TITLE
retinanet fpn 训练问题

### ISSUE THREAD

**Issue by violet2422** [WZMIAOMIAO/deep-learning-for-image-processing#503]
博主您好，感谢开源项目，同时感谢您的项目对我们的极大帮助！！！
我在使用Retinanet进行训练遇到的情况我的torch版本是1.8，是不是和版本有关
```ssh://root@211.82.238.201:8106/opt/conda/bin/python -u /root/.pycharm_helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 0.0.0.0 --port 40221 --file /ws/Ww/retinanet/train.py
pydev debugger: process 315 is connecting

Connected to pydev debugger (build 201.6668.115)
Namespace(amp=True, aspect_ratio_group_factor=-1, batch_size=2, data_path='../PvData', device='cuda:0', epochs=15, num_classes=3, output_dir='./save_weights', resume='', start_epoch=0)
Using cuda device training.
Using 0 dataloader workers
_IncompatibleKeys(missing_keys=['head.classification_head.cls_logits.weight', 'head.classification_head.cls_logits.bias'], unexpected_keys=[])
Epoch: [0] [ 0/397] eta: 0:05:11.578399 lr: 0.000018 loss: 1.6347 (1.6347) classification: 1.1716 (1.1716) bbox_regression: 0.4631 (0.4631) time: 0.7848 data: 0.0474 max mem: 1587
/opt/conda/conda-bld/pytorch_1614378083779/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [0,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.
/opt/conda/conda-bld/pytorch_1614378083779/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [1,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.
/opt/conda/conda-bld/pytorch_1614378083779/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [2,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.
/opt/conda/conda-bld/pytorch_1614378083779/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [3,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.
/opt/conda/conda-bld/pytorch_1614378083779/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [4,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.
Traceback (most recent call last):
File "/ws/Ww/retinanet/train_utils/train_eval_utils.py", line 33, in train_one_epoch
loss_dict = model(images, targets)
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
result = self.forward(*input, **kwargs)
File "/ws/Ww/retinanet/network_files/retinanet.py", line 504, in forward
losses = self.compute_loss(targets, head_outputs, anchors)
File "/ws/Ww/retinanet/network_files/retinanet.py", line 369, in compute_loss
return self.head.compute_loss(targets, head_outputs, anchors, matched_idxs)
File "/ws/Ww/retinanet/network_files/retinanet.py", line 214, in compute_loss
"classification": self.classification_head.compute_loss(targets, head_outputs, matched_idxs),
File "/ws/Ww/retinanet/network_files/retinanet.py", line 81, in compute_loss
losses.append(sigmoid_focal_loss(cls_logits_per_img[valid_idxs_per_img],
RuntimeError: CUDA error: device-side assert triggered```

**Comment by violet2422** [comment]
感谢您的及时回复！我会持续关注您的项目



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月29日(周二) 下午4:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WZMIAOMIAO/deep-learning-for-image-processing] retinanet fpn 训练问题 (Issue #503)




 
很有可能，建议使用Pytorch1.7.1或者1.10，避开1.8和1.9。最简单的测试办法是你用CPU去训练，看会不会报错，如果CPU不报错就是Pytorch和CUDA环境问题了。关于Pytorch安装，可以参考：https://blog.csdn.net/qq_37541097/article/details/120951214
