### ISSUE TITLE
使用FCN过程中的问题

### ISSUE THREAD

**Issue by Oision-hub** [WZMIAOMIAO/deep-learning-for-image-processing#504]
up，你好
我在运行FCN（pytorch版本）的`train.py`时候出现这样的错误，是什么原因导致的呀？
```python
Traceback (most recent call last):
  File "/home/oision/PycharmProjects/DeepLearning/FCN/train.py", line 210, in <module>
    main(args)
  File "/home/oision/PycharmProjects/DeepLearning/FCN/train.py", line 118, in main
    optimizer = torch.optim.SGD(
  File "/home/oision/PycharmProjects/DeepLearning/venv/lib/python3.8/site-packages/torch/optim/sgd.py", line 101, in __init__
    super(SGD, self).__init__(params, defaults)
  File "/home/oision/PycharmProjects/DeepLearning/venv/lib/python3.8/site-packages/torch/optim/optimizer.py", line 54, in __init__
    self.add_param_group(param_group)
  File "/home/oision/PycharmProjects/DeepLearning/venv/lib/python3.8/site-packages/torch/optim/optimizer.py", line 289, in add_param_group
    raise ValueError("some parameters appear in more than one parameter group")
ValueError: some parameters appear in more than one parameter group
```

**Comment by WZMIAOMIAO** [comment]
麻烦先按照项目`requirements.txt`文件把环境配置好。如果还有问题在提问。
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/master/pytorch_segmentation/fcn/requirements.txt

**Comment by Oision-hub** [comment]
我将各依赖库均换成了`requirements.txt`中相同的版本，但这问题依旧存在。

**Comment by WZMIAOMIAO** [comment]
可我这边从没遇到你说的问题，也没听别人反馈过类似问题。你自己在好好检查下吧，看是不是你自己改动了某些代码导致的。
