### ISSUE TITLE
Flask:  BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by sihuo521** [WZMIAOMIAO/deep-learning-for-image-processing#521]
1. bug:
2022-04-13 07:22:39,830 - model_server_photovoltaic - ERROR - Exception on /chaojiben [POST]
Traceback (most recent call last):
  File "/root/anaconda3/envs/cjb/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/anaconda3/envs/cjb/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/anaconda3/envs/cjb/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/anaconda3/envs/cjb/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/detector/model_service/photovoltaic/model_server_photovoltaic.py", line 65, in get_prediction
    print("response:", response)
**BrokenPipeError: [Errno 32] Broken pipe**

2. 代码：

      @app.route("/predict", methods=["POST", "GET"])
      def get_prediction():
              logger_main = flask_exec.logger_main
              logger_main.info("request.method:{}".format(request.method))
              if request.method == "POST":
                  response = request.get_json()
                  logger_main.info("response:{}".format(response))
                  print("response:", response)
                  data_dict = {"message": "received successfully"}
                  executor.submit(model_infer, response)
                  print('model_infer running')
                  return jsonify(data_dict)
3. 别人发送json串信息，会发生以上错误，大神有遇到这种问题吗

**Comment by WZMIAOMIAO** [comment]
自己改过代码遇到的问题自行解决吧，我也不清楚你这是什么问题。
