### ISSUE TITLE
RuntimeError: Trying to pass too many CPU scalars to CUDA kernel!

### ISSUE THREAD

**Issue by why228430** [WZMIAOMIAO/deep-learning-for-image-processing#54]
Thanks for sharing you code . when I run 'python train_mobilenet.py ',I meet the problem.How I can do to solve the error!

Traceback (most recent call last):
  File "train_mobilenet.py", line 157, in <module>
    main()
  File "train_mobilenet.py", line 91, in main
    train_loss=train_loss, train_lr=learning_rate)
  File "/home/dl/桌面/faster_rcnn/train_utils/train_eval_utils.py", line 33, in train_one_epoch
    loss_dict = model(images, targets)
  File "/home/dl/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dl/桌面/faster_rcnn/network_files/faster_rcnn_framework.py", line 87, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/dl/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dl/桌面/faster_rcnn/network_files/rpn_function.py", line 615, in forward
    labels, matched_gt_boxes = self.assign_targets_to_anchors(anchors, targets)
  File "/home/dl/桌面/faster_rcnn/network_files/rpn_function.py", line 410, in assign_targets_to_anchors
    matched_idxs = self.proposal_matcher(match_quality_matrix)
  File "/home/dl/桌面/faster_rcnn/network_files/det_utils.py", line 347, in __call__
    matches[below_low_threshold] = torch.tensor(self.BELOW_LOW_THRESHOLD)  # -1
RuntimeError: Trying to pass too many CPU scalars to CUDA kernel!

**Comment by WZMIAOMIAO** [comment]
你可以重新克隆下我的代码，我已经把这个问题修复了，主要问题是在使用torch.tensor()这个方法(我怀疑是没有指认设备的原因)，我直接把这个方法替换成对应常数了，例如：
```
torch.tensor(0)
```
替换成
```
0
```

**Comment by why228430** [comment]
谢谢！问题已解决

**Comment by why228430** [comment]
看了你的视频收获很多。弱弱问一句，faster-rcnn的视频什么时候更新？

**Comment by super-wz** [comment]
可能本周吧

**Comment by why228430** [comment]
features = list(features.values())
        # 计算每个预测特征层上的预测目标概率和bboxes regression参数
        # objectness和pred_bbox_deltas都是list
        objectness, pred_bbox_deltas = self.head(features)
        # 生成一个batch图像的所有anchors信息,list(tensor)元素个数等于batch_size
        anchors = self.anchor_generator(images, features)
关于这个地方我有两点不理解：（1）骨架网络学习到的特征图包含gt框的信息吗？（2）经过head函数对特征图进行3*3卷积操作，然后经过2个1*1卷积分别学习目标前景分数和边界框回归参数，但是这个时候原图上还没有生成anchor，网络是怎么学习的目标前景分数和边界框回归参数的？

**Comment by WZMIAOMIAO** [comment]
anchors假想是一直存在的，刚开始训练预测时你可以理解为网络瞎预测的（最开始网络并不知道anchors的存在），但计算损失时，由于是已anchors作为参考的，所以在反向传播误差时，网络才慢慢开始理解anchors的存在，并已anchors作为参照进行预测回归参数。

**Comment by why228430** [comment]
讲的很明白，谢谢！
