### ISSUE TITLE
RuntimeError: shape '[4, 3, 11, 72, 72]' is invalid for input of size 311040【train.py】

### ISSUE THREAD

**Issue by developer-young** [WZMIAOMIAO/deep-learning-for-image-processing#556]
**System information**
* Have I written custom code: `Yes`
* OS Platform(e.g., window10 or Linux Ubuntu 16.04): `Unbuntu 20.04`
* Python version: `Python3.8`
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3): `Pytorch1.7`
* Use GPU or not: `GPU`
* CUDA/cuDNN version(if you use GPU): `10.2`
* The network you trained(e.g., Resnet34 network): `yolov3-spp`

**Describe the current behavior**
自定义数据集，运行`train.py`，程序报错。
**Error info / logs**
```
Namespace(amp=False, batch_size=4, cache_images=False, cfg='cfg/my_yolov3.cfg', data='data/my_data.data', device='cuda:0', epochs=30, freeze_layers=False, hyp='cfg/hyp.yaml', img_size=512, multi_scale=True, name='', notest=False, rect=False, savebest=False, single_cls=False, weights='weights/yolov3spp-voc-512.pt')
Start Tensorboard with "tensorboard --logdir=runs", view at http://localhost:6006/
Using cuda device training.
Using multi_scale training, image range[320, 736]
WARNING: smart bias initialization failure. math domain error
WARNING: smart bias initialization failure. math domain error
Model Summary: 225 layers, 6.25679e+07 parameters, 6.25679e+07 gradients
Caching labels (4410 found, 0 missing, 0 empty, 0 duplicate, for 4410 images): 100%|██████████| 4410/4410 [00:00<00:00, 9737.86it/s]
Caching labels (1890 found, 0 missing, 0 empty, 0 duplicate, for 1890 images): 100%|██████████| 1890/1890 [00:00<00:00, 9707.53it/s]
loading eval info for coco tools.: 100%|██████████| 1890/1890 [00:00<00:00, 4537.23it/s]
creating index...
index created!
starting traning for 30 epochs...
Using 4 dataloader workers
Traceback (most recent call last):
  File "/root/yd/yolov3_spp/train.py", line 309, in <module>
    train(hyp)
  File "/root/yd/yolov3_spp/train.py", line 205, in train
    mloss, lr = train_util.train_one_epoch(model, optimizer, train_dataloader,
  File "/root/yd/yolov3_spp/train_utils/train_eval_utils.py", line 58, in train_one_epoch
    pred = model(imgs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/yd/yolov3_spp/models.py", line 227, in forward
    return self.forward_once(x, verbose=verbose)
  File "/root/yd/yolov3_spp/models.py", line 246, in forward_once
    yolo_out.append(module(x))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/yd/yolov3_spp/models.py", line 177, in forward
    p = p.view(bs, self.na, self.no, self.ny, self.nx).permute(0, 1, 3, 4, 2).contiguous()  # prediction
RuntimeError: shape '[4, 3, 11, 72, 72]' is invalid for input of size 311040

Process finished with exit code 1

```

**Comment by WZMIAOMIAO** [comment]
你用pascal voc数据集跑通了吗？还有请提供可复现错误的代码，要不然没法排查。

**Comment by WZMIAOMIAO** [comment]
还有检查一下是否使用的是最新的代码。

**Comment by developer-young** [comment]
谢谢了，已解决。

**Comment by WZMIAOMIAO** [comment]
> 谢谢了，已解决。

是什么问题导致的，如果是我的代码有问题，麻烦提供一些详细信息。
