### ISSUE TITLE
在使用retinanet进行多GPU训练时报错

### ISSUE THREAD

**Issue by LKssssZz** [WZMIAOMIAO/deep-learning-for-image-processing#559]
导师好！(狗头)
我在retinanet的backbone上面进行了修改，添加了cbam模块，使用单GPU训练正常，不会报错。但是使用多GPU却不行，我翻译了下大概是参数回传的问题，网上查了下也没搞清楚，可以帮忙看下吗？？其实这个情况我在跑ssd时候也是这个错误，就没管，没想到这里又出错了……
报错信息如下：
Start training
/home/lb511/anaconda3/envs/lhaozz/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811803361/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/lb511/anaconda3/envs/lhaozz/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811803361/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

Epoch: [0]  [  0/132]  eta: 0:03:01.012762  lr: 0.000173  loss: 1.8379 (1.8379)  bbox_regression: 0.6653 (0.6653)  classification: 1.1726 (1.1726)  time: 1.3713  data: 0.3985  max mem: 8638
Traceback (most recent call last):
  File "/home/lhaozz/hand_retinanet/train_multi_GPU.py", line 260, in <module>
    main(args)
  File "/home/lhaozz/hand_retinanet/train_multi_GPU.py", line 141, in main
    mean_loss, lr = utils.train_one_epoch(model, optimizer, data_loader,
  File "/home/lhaozz/hand_retinanet/train_utils/train_eval_utils.py", line 33, in train_one_epoch
    loss_dict = model(images, targets)
  File "/home/lb511/anaconda3/envs/lhaozz/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lb511/anaconda3/envs/lhaozz/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 873, in forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():

**RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 12 13 14 15 25 26 27 28 38 39 40 41 51 52 53 54 67 68 69 70 80 81 82 83 93 94 95 96 106 107 108 109 119 120 121 122 132 133 134 135 148 149 150 151 161 162 163 164 174 175 176 177
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error**

顺便问个小问题，混合精度训练我使用的是 两张3080，cpu是r9 5950x 16核心，，平时是一般打开就行吗？

**Comment by WZMIAOMIAO** [comment]
没有遇到到，猜测是你网络的问题。

**Comment by LKssssZz** [comment]
> 没有遇到过，猜测是你网络的问题。

可是我就是简单的加了个模块呀，不能多GPU有点难顶/(ㄒoㄒ)/~~

**Comment by WZMIAOMIAO** [comment]
你如果不加能用多GPU训练吗？

**Comment by LKssssZz** [comment]
> 你如果不加能用多GPU训练吗？

不加的话是可以多GPU的，加了的话也是可以单GPU的不报错，但是多GPU就会报上面的错。。
模型的话cbam就是加在了resnet的layer层后，，应该不会有太大错误吧？不然单GPU也会报错

**Comment by WZMIAOMIAO** [comment]
根据你的消融实验分析，就是你加入新模块导致的，具体原因就不清楚了，可能是你自己使用的方式有问题。

**Comment by LKssssZz** [comment]
> 根据你的消融实验分析，就是你加入新模块导致的，具体原因就不清楚了，可能是你自己使用的方式有问题。

好吧那我再自己修改研究下。。最后顺便问下混合精度训练我使用的是 两张3080，cpu是r9 5950x 16核心，，平时是一般打开就行吗？

**Comment by WZMIAOMIAO** [comment]
你自己可以对比一下用和不用的区别，不能保证所有情况下开amp比不开好。

**Comment by LKssssZz** [comment]
> 你自己可以对比一下用和不用的区别，不能保证所有情况下开amp比不开好。

感谢回答，那我就把 issue 关了。

**Comment by insist-arui** [comment]
> 你自己可以对比一下用和不用的区别，不能保证所有情况下开amp比不开好。



> > 没有遇到过，猜测是你网络的问题。
> 
> 可是我就是简单的加了个模块呀，不能多GPU有点难顶/(ㄒoㄒ)/~~

您好，您现在解决这个问题了么
