### ISSUE TITLE
RuntimeError: Arguments for call are not valid.

### ISSUE THREAD

**Issue by Forstun** [WZMIAOMIAO/deep-learning-for-image-processing#58]
Thanks for your code. when i run the code 'python train_res50_fpn.py',i meet this problem.How can i resolve it? 
Traceback (most recent call last):
  File "train_res50_fpn.py", line 3, in <module>
    from network_files.faster_rcnn_framework import FasterRCNN, FastRCNNPredictor
  File "/home/yzhou/IpFPN/faster_rcnn/network_files/faster_rcnn_framework.py", line 4, in <module>
    from network_files.rpn_function import AnchorsGenerator, RPNHead, RegionProposalNetwork
  File "/home/yzhou/IpFPN/faster_rcnn/network_files/rpn_function.py", line 6, in <module>
    from network_files import det_utils
  File "/home/yzhou/IpFPN/faster_rcnn/network_files/det_utils.py", line 16, in <module>
    class BalancedPositiveNegativeSampler(object):
  File "/home/yzhou/.pyenv/versions/anaconda3-5.3.1/envs/CenterNet/lib/python3.6/site-packages/torch/jit/__init__.py", line 1274, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/home/yzhou/.pyenv/versions/anaconda3-5.3.1/envs/CenterNet/lib/python3.6/site-packages/torch/jit/__init__.py", line 1115, in _compile_and_register_class
    _jit_script_class_compile(qualified_name, ast, rcb)
RuntimeError:
Arguments for call are not valid.
The following variants are available:

  aten::index_put_(Tensor(a!) self, Tensor?[] indices, Tensor values, bool accumulate=False) -> (Tensor(a!)):
  Expected a value of type 'Tensor' for argument 'values' but instead found type 'int'.

  aten::index_put_(Tensor(a!) self, Tensor[] indices, Tensor values, bool accumulate=False) -> (Tensor(a!)):
  Expected a value of type 'List[Tensor]' for argument 'indices' but instead found type 'List[Optional[Tensor]]'.

The original call is:
  File "/home/yzhou/IpFPN/faster_rcnn/network_files/det_utils.py", line 85
            )

            pos_idx_per_image_mask[pos_idx_per_image] = 1
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            neg_idx_per_image_mask[neg_idx_per_image] = 1

**Comment by WZMIAOMIAO** [comment]
upgrade pytorch to 1.6.0
