### ISSUE TITLE
ValueError: numpy.ufunc size changed

### ISSUE THREAD

**Issue by guyueyanfeng** [WZMIAOMIAO/deep-learning-for-image-processing#584]
**System information**
Windows10
Python 3.7
torch==1.7.1
CPU
backbone: MobileNet

**Describe the current behavior**
The program break when I run "train_mobilenetv2.py" after I prepared the environment.

**Error info / logs**

Traceback (most recent call last):
  File "E:/deep-learning-for-image-processing/pytorch_object_detection/faster_rcnn/train_mobilenetv2.py", line 11, in <module>
    from train_utils import GroupedBatchSampler, create_aspect_ratio_groups
  File "E:\deep-learning-for-image-processing\pytorch_object_detection\faster_rcnn\train_utils\__init__.py", line 3, in <module>
    from .coco_utils import get_coco_api_from_dataset
  File "E:\deep-learning-for-image-processing\pytorch_object_detection\faster_rcnn\train_utils\coco_utils.py", line 4, in <module>
    from pycocotools.coco import COCO
  File "F:\Anaconda\lib\site-packages\pycocotools\coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "F:\Anaconda\lib\site-packages\pycocotools\mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "__init__.pxd", line 918, in init pycocotools._mask
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

![image](https://user-images.githubusercontent.com/30621422/176423356-cc0acf7c-731f-4c37-9918-616782912537.png)
![image](https://user-images.githubusercontent.com/30621422/176423445-8354f018-8254-4c60-96e9-63a893d194c3.png)

**Comment by WZMIAOMIAO** [comment]
This problem may be caused by the version of numpy. You can try to update the version of numpy to `1.21.3`.

**Comment by guyueyanfeng** [comment]
Yes, it works when I update the numpy to 1.21.3. Thanks !!
>
