### ISSUE TITLE
Own data training error useing SSD model.

### ISSUE THREAD

**Issue by uniyushu** [WZMIAOMIAO/deep-learning-for-image-processing#61]
When I use my own dataset for training, I meet the problem. My images format are RGB. Can you help me solve the problem?
**System information**
* OS Platform(e.g., window10 or Linux Ubuntu 16.04):Linux Ubuntu 16.04
* Python version:3.7
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3): Pytorch1.5
* CUDA/cuDNN version(if you use GPU): CUDA10.1
* The network you trained(e.g., Resnet34 network): SSD

**Error info / logs**
Namespace(batch_size=4, device='cuda:0', epochs=15, output_dir='./save_weights', resume='', start_epoch=0)
Using cuda device training.
Using 4 dataloader workers
missing_keys:  ['conf.0.weight', 'conf.0.bias', 'conf.1.weight', 'conf.1.bias', 'conf.2.weight', 'conf.2.bias', 'conf.3.weight', 'conf.3.bias', 'conf.4.weight', 'conf.4.bias', 'conf.5.weight', 'conf.5.bias', 'compute_loss.dboxes', 'postprocess.dboxes_xywh']
unexpected_keys:  []
Epoch: [0]  [     0/104637]  eta: 9 days, 4:57:54.872362  lr: 0.000500  total_losses: 10.8151 (10.8151)  time: 7.6022  data: 7.0505  max mem: 1072
Epoch: [0]  [    50/104637]  eta: 16:05:47.249883  lr: 0.000500  total_losses: 4.7562 (6.0402)  time: 0.4383  data: 0.3700  max mem: 1169
Epoch: [0]  [   100/104637]  eta: 15:38:36.884186  lr: 0.000500  total_losses: 4.0707 (5.2116)  time: 0.4212  data: 0.3559  max mem: 1169
Traceback (most recent call last):
  File "train_ssd300_object365.py", line 181, in <module>
    main(args)
  File "train_ssd300_object365.py", line 121, in main
    train_lr=learning_rate)
  File "/data/ssd/train_utils/train_eval_utils.py", line 27, in train_one_epoch
    for images, targets in metric_logger.log_every(data_loader, print_freq, header):
  File "/data/ssd/train_utils/distributed_utils.py", line 204, in log_every
    for obj in iterable:
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 838, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/ssd/object_dataset.py", line 82, in __getitem__
    image, target = self.transform(image, target)
  File "/data/ssd/transform.py", line 15, in __call__
    image, target = trans(image, target)
  File "/data/ssd/transform.py", line 181, in __call__
    image = self.normalize(image)
  File "/opt/conda/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 166, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/opt/conda/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean).div_(std)
RuntimeError: output with shape [1, 300, 300] doesn't match the broadcast shape [3, 300, 300]

**Comment by WZMIAOMIAO** [comment]
I guess some of the images in the dataset are in gray format.  you can add these code into my_dataset.py( 49 line) to find gray image.
```
if image.mode != "RGB":
    raise ValueError("image: {} is not RGB format.".format(img_path))
```

**Comment by uniyushu** [comment]
> I guess some of the images in the dataset are in gray format. you can add these code into my_dataset.py( 49 line) to find gray image.
> 
> ```
> if image.mode != "RGB":
>     raise ValueError("image: {} is not RGB format.".format(img_path))
> ```

You are right, there are some gray format images in my dataset.  After I convert all the gray images to RGB images.
 It starts training.
