### ISSUE TITLE
使用swin_transformer构建fpn_backbone出现的错误

### ISSUE THREAD

**Issue by ts19970816** [WZMIAOMIAO/deep-learning-for-image-processing#618]
Traceback (most recent call last):
  File "/home/bhts/project/mask_rcnn_attention/mask_rcnn_v1/backbone/swin_transformer_fpn_model.py", line 8, in <module>
    from backbone.swin import swin_base_patch4_window7_224
  File "/home/bhts/project/mask_rcnn_attention/mask_rcnn_v1/backbone/__init__.py", line 3, in <module>
    from .swin_transformer_fpn_model import transformer_fpn_backbone,resnet_fpn_backbone
  File "/home/bhts/project/mask_rcnn_attention/mask_rcnn_v1/backbone/swin_transformer_fpn_model.py", line 149, in <module>
    transformer_fpn_backbone()
  File "/home/bhts/project/mask_rcnn_attention/mask_rcnn_v1/backbone/swin_transformer_fpn_model.py", line 135, in transformer_fpn_backbone
    new_backbone = create_feature_extractor(backbone, return_layers)
  File "/home/bhts/anaconda3/lib/python3.7/site-packages/torchvision/models/feature_extraction.py", line 485, in create_feature_extractor
    graph = tracer.trace(model)
  File "/home/bhts/anaconda3/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 715, in trace
    (self.create_arg(fn(*args)),),
  File "/home/bhts/project/mask_rcnn_attention/mask_rcnn_v1/backbone/swin.py", line 554, in forward
    x, H, W = self.patch_embed(x)
  File "/home/bhts/anaconda3/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 693, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "/home/bhts/anaconda3/lib/python3.7/site-packages/torchvision/models/feature_extraction.py", line 83, in call_module
    out = forward(*args, **kwargs)
  File "/home/bhts/anaconda3/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 686, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "/home/bhts/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/bhts/project/mask_rcnn_attention/mask_rcnn_v1/backbone/swin.py", line 105, in forward
    pad_input = (H % self.patch_size[0] != 0) or (W % self.patch_size[1] != 0)
  File "/home/bhts/anaconda3/lib/python3.7/site-packages/torch/fx/proxy.py", line 286, in __bool__
    return self.tracer.to_bool(self)
  File "/home/bhts/anaconda3/lib/python3.7/site-packages/torch/fx/proxy.py", line 162, in to_bool
    raise TraceError('symbolically traced variables cannot be used as inputs to control flow')
torch.fx.proxy.TraceError: symbolically traced variables cannot be used as inputs to control flow
博主，你好，当我使用swin_transfromer构建fpn_backbone出现这样的错误，请指教

**Comment by WZMIAOMIAO** [comment]
改代码的问题请自行解决，谢谢。

**Comment by ts19970816** [comment]
好的，谢谢
