### ISSUE TITLE
训练自己的关键点检测模型时，训练集loss降的很低，测试时所有COCO测试指标从开始到结束都为0。

### ISSUE THREAD

**Issue by xuan-xuan6** [WZMIAOMIAO/deep-learning-for-image-processing#630]
您好，我使用您的hrnet代码进行数据集训练。我将我的数据进行关键点标注后，转成COCO数据集格式，更改关键点的个数，并可以成功训练和测试，但测试时coco的测试指标从头到尾一直为0，且使用训练结束后的权重进行推断时，效果很差，我输入的图片大小为256x256，训练集800多张，是因为我训练集数量太少了吗？

**Comment by WZMIAOMIAO** [comment]
可能你数据集格式有问题吧，你自己做的数据集我也不清楚。

**Comment by xuan-xuan6** [comment]
好的，现在已经使用openpose去做这个项目啦，不过还是很感谢您的回复，谢谢！



在 2022-08-28 19:55:23，"WuZhe" ***@***.***> 写道：

可能你数据集格式有问题吧，你自己做的数据集我也不清楚。

**Comment by rrryan2016** [comment]
求助一下题主，请问有自标注数据集转化成COCO标注格式的工具么？

**Comment by 1334233852** [comment]
> 您好，我使用您的hrnet代码进行数据集训练。我将我的数据进行关键点标注后，转成COCO数据集格式，更改关键点的个数，并可以成功训练和测试，但测试时coco的测试指标从头到尾一直为0，且使用训练结束后的权重进行推断时，效果很差，我输入的图片大小为256x256，训练集800多张，是因为我训练集数量太少了吗？

同学您好，请问你的数据集关键点个数不是17,用coco评估，代码是哪些做了调整

**Comment by 1334233852** [comment]
> 可能你数据集格式有问题吧，你自己做的数据集我也不清楚。

你好，我的数据集关键点是8个，coco是17个，我做了相应的代码调试，还是出现这个问题Traceback (most recent call last):
  File "/media/cmf/EEA2072AA206F73D/VOS_related_Project/KeyPoint/HRNet/train_multi_GPU.py", line 272, in <module>
    main(args)
  File "/media/cmf/EEA2072AA206F73D/VOS_related_Project/KeyPoint/HRNet/train_multi_GPU.py", line 164, in main
    key_info = utils.evaluate(model, data_loader_test, device=device,
  File "/home/cmf/anaconda3/envs/xmem-repro/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/media/cmf/EEA2072AA206F73D/VOS_related_Project/KeyPoint/HRNet/train_utils/train_eval_utils.py", line 115, in evaluate
    coco_info = key_metric.evaluate()
  File "/media/cmf/EEA2072AA206F73D/VOS_related_Project/KeyPoint/HRNet/train_utils/coco_eval.py", line 128, in evaluate
    self.coco_evaluator.evaluate()
  File "/home/cmf/anaconda3/envs/xmem-repro/lib/python3.9/site-packages/pycocotools/cocoeval.py", line 148, in evaluate
    self.ious = {(imgId, catId): computeIoU(imgId, catId) \
  File "/home/cmf/anaconda3/envs/xmem-repro/lib/python3.9/site-packages/pycocotools/cocoeval.py", line 148, in <dictcomp>
    self.ious = {(imgId, catId): computeIoU(imgId, catId) \
  File "/home/cmf/anaconda3/envs/xmem-repro/lib/python3.9/site-packages/pycocotools/cocoeval.py", line 229, in computeOks
    e = (dx**2 + dy**2) / vars / (gt['area']+np.spacing(1)) / 2
ValueError: operands could not be broadcast together with shapes (8,) (17,)
