### ISSUE TITLE
多GPU训练出错，能否帮助看下可能是什么问题

### ISSUE THREAD

**Issue by Yuhuoo** [WZMIAOMIAO/deep-learning-for-image-processing#661]
**System information**
* Have I written custom code: 没有
* OS Platform(e.g., window10 or Linux Ubuntu 16.04):Linux Ubuntu 16.04
* Python version: 3.8
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3): pytorch
* Use GPU or not: 使用GPU
* CUDA/cuDNN version(if you use GPU):
* The network you trained(e.g., Resnet34 network): MaskRCNN

**Describe the current behavior**
多GPU训练pascal voc数据集出错
**Error info / logs**
Traceback (most recent call last):
  File "train_multi_GPU.py", line 269, in <module>
    main(args)
  File "train_multi_GPU.py", line 147, in main
    mean_loss, lr = utils.train_one_epoch(model, optimizer, data_loader,
  File "/hy-tmp/MaskFCN/mask_rcnn/train_utils/train_eval_utils.py", line 27, in train_one_epoch
    images = list(image.to(device) for image in images)
  File "/hy-tmp/MaskFCN/mask_rcnn/train_utils/train_eval_utils.py", line 27, in <genexpr>
    images = list(image.to(device) for image in images)
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 548, in __getattr__
    raise AttributeError(name)
AttributeError: to
Traceback (most recent call last):
  File "train_multi_GPU.py", line 269, in <module>
    main(args)
  File "train_multi_GPU.py", line 147, in main
    mean_loss, lr = utils.train_one_epoch(model, optimizer, data_loader,
  File "/hy-tmp/MaskFCN/mask_rcnn/train_utils/train_eval_utils.py", line 27, in train_one_epoch
    images = list(image.to(device) for image in images)
  File "/hy-tmp/MaskFCN/mask_rcnn/train_utils/train_eval_utils.py", line 27, in <genexpr>
    images = list(image.to(device) for image in images)
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 548, in __getattr__
    raise AttributeError(name)
AttributeError: to
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3891) of binary: /usr/bin/python3.8

**Comment by Yuhuoo** [comment]
多卡训练COCO数据集是可以的，单卡训练pascal voc也是可以的，多卡训练pascal voc就出错了，没有改动代码

**Comment by Yuhuoo** [comment]
> 看不出错误来源，你是用的官方pascal voc吗？能提供最小复现错误代码吗？

是用的官方的pascal voc数据集，读取数据的时候会有数据缺失跳过的log，不知道和这个错误会不会有关系。
最小复现错误代码是指完整的错误log吗？

**Comment by jjjjjjjjj58** [comment]
> 

我也有同样的报错，使用的是train_multi_gpu_using_launch.py文件

**Comment by yuanxinshui** [comment]
我也出现了同样的问题
