### ISSUE TITLE
训练错误model.to(device)

### ISSUE THREAD

**Issue by bibibabibo26** [WZMIAOMIAO/deep-learning-for-image-processing#664]
Traceback (most recent call last):
  File "/home/zyt/detection/deep-learning-for-image-processing-master/pytorch_object_detection/faster_rcnn/train_mobilenetv2.py", line 224, in <module>
    main()
  File "/home/zyt/detection/deep-learning-for-image-processing-master/pytorch_object_detection/faster_rcnn/train_mobilenetv2.py", line 114, in main
    model.to(device)
  File "/home/zyt/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 899, in to
    return self._apply(convert)
  File "/home/zyt/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/zyt/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/zyt/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/zyt/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 593, in _apply
    param_applied = fn(param)
  File "/home/zyt/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 897, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
KeyboardInterrupt

**Comment by WZMIAOMIAO** [comment]
请严格按照问题模板提问，谢谢。
