### ISSUE TITLE
predict issue

### ISSUE THREAD

**Issue by menggerSherry** [WZMIAOMIAO/deep-learning-for-image-processing#72]
模型训练完成后，进行predict时出现如下操作：

Traceback (most recent call last):
  File "/Users/mengxiangyu/Desktop/faster_rcnn/predict.py", line 47, in <module>
    model.load_state_dict(torch.load(train_weights)["model"])
  File "/Users/mengxiangyu/anaconda3/envs/th1.6/lib/python3.7/site-packages/torch/serialization.py", line 577, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/Users/mengxiangyu/anaconda3/envs/th1.6/lib/python3.7/site-packages/torch/serialization.py", line 241, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: [enforce fail at inline_container.cc:144] . PytorchStreamReader failed reading zip archive: failed finding central directory

是什么原因，是否是加载的模型有问题

**Comment by WZMIAOMIAO** [comment]
猜测是你权重路径设置有问题，训练好的权重是```.pth```结尾的文件，怎么错误提示会有```zip archive```，自己好好检查下。
