### ISSUE TITLE
Faster R-CNN torchsummary problem

### ISSUE THREAD

**Issue by fwt1226** [WZMIAOMIAO/deep-learning-for-image-processing#724]
Traceback (most recent call last):
  File "/home/lunar/音乐/winCode_train_coco_dataset_resnet50/all_train.py", line 260, in <module>
    main(args)
  File "/home/lunar/音乐/winCode_train_coco_dataset_resnet50/all_train.py", line 128, in main
    model = create_model(num_classes=args.num_classes + 1)
  File "/home/lunar/音乐/winCode_train_coco_dataset_resnet50/all_train.py", line 62, in create_model
    summary(model, (3, 640, 640))
  File "/home/lunar/anaconda3/envs/pytorch/lib/python3.8/site-packages/torchsummary/torchsummary.py", line 75, in summary
    model(*x)
  File "/home/lunar/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lunar/音乐/winCode_train_coco_dataset_resnet50/network_files/faster_rcnn_framework.py", line 82, in forward
    images, targets = self.transform(images, targets)  # 对图像进行预处理
  File "/home/lunar/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1123, in _call_impl
    hook_result = hook(self, input, result)
  File "/home/lunar/anaconda3/envs/pytorch/lib/python3.8/site-packages/torchsummary/torchsummary.py", line 22, in hook
    summary[m_key]["output_shape"] = [
  File "/home/lunar/anaconda3/envs/pytorch/lib/python3.8/site-packages/torchsummary/torchsummary.py", line 23, in <listcomp>
    [-1] + list(o.size())[1:] for o in output
AttributeError: 'ImageList' object has no attribute 'size

不知道该怎么改qwq 求解,感谢!

**Comment by SherlockBULABULA** [comment]
有没有试过把中文路径改了

**Comment by fwt1226** [comment]
> 有没有试过把中文路径改了

改过了也还是报这个错qwq

**Comment by WZMIAOMIAO** [comment]
不好意思没用过torchsummary
