### ISSUE TITLE
多卡跑hrnet时出现错误

### ISSUE THREAD

**Issue by srg1234567** [WZMIAOMIAO/deep-learning-for-image-processing#738]
在训练完第一个epoch就出现了这样的错误，请问是出了什么问题吗
IoU metric: keypoints
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.358
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.679
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.335
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.364
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.361
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.451
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.755
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.457
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.426
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.487
Traceback (most recent call last):
  File "/media/data1/sangrg/HRNet/train_multi_GPU.py", line 272, in <module>
    main(args)
  File "/media/data1/sangrg/HRNet/train_multi_GPU.py", line 168, in main
    if args.rank in [-1, 0]:
AttributeError: 'Namespace' object has no attribute 'rank'

**Comment by CKtm** [comment]
同样的问题 请问解决了吗
