### ISSUE TITLE
TensorFlow 2.4.1使用mobilenetv3,自己训练的权重.ckpt转.h5，遇到错误

### ISSUE THREAD

**Issue by QLW-07** [WZMIAOMIAO/deep-learning-for-image-processing#746]
Traceback (most recent call last):
  File "/home/xt/tf2.3-master/mobilenet_v3/trans_v3_weights.py", line 66, in <module>
    main()
  File "/home/xt/tf2.3-master/mobilenet_v3/trans_v3_weights.py", line 60, in main
    weights = rename_var(ckpt_path, m_info)
  File "/home/xt/tf2.3-master/mobilenet_v3/trans_v3_weights.py", line 35, in rename_var
    assert k in var_dict, "{} not in var_dict".format(k)
AssertionError: Conv/kernel not in var_dict

**Comment by zhGlade** [comment]
请问解决了吗 遇到一样的问题了
