### ISSUE TITLE
高版本的torch报错未发现torch._six

### ISSUE THREAD

**Issue by water107** [WZMIAOMIAO/deep-learning-for-image-processing#747]
**System information**
* Have I writtenTraceback (most recent call last):
  File "C:\Work\Pycharm\faster_rcnn\train_mobilenetv2.py", line 11, in <module>
    from train_utils import GroupedBatchSampler, create_aspect_ratio_groups
  File "C:\Work\Pycharm\faster_rcnn\train_utils\__init__.py", line 4, in <module>
    from .coco_eval import CocoEvaluator
  File "C:\Work\Pycharm\faster_rcnn\train_utils\coco_eval.py", line 7, in <module>
    import torch._six
ModuleNotFoundError: No module named 'torch._six'

进程已结束,退出代码1

**Comment by mjc-ddj** [comment]
我也遇到了同样的问题，请问你解决了吗

**Comment by mjc-ddj** [comment]
import torch._six我直接将这一段注释掉了，debug并没有报错

**Comment by linwqwhu** [comment]
有两种方式
```python
# 把import语句注释掉，并添加string_classes = str
# from torch._six import *
string_classes = str

# 然后再后面找到使用__six函数的地方，把torch.__six.string_classes改为string_classes，如：
if isinstance(resFile, string_classes):

# 也可以直接改成：
if isinstance(resFile, str):
```
