### ISSUE TITLE
训练自己数据集检测时出现画图颜色的错误

### ISSUE THREAD

**Issue by DeaLong** [WZMIAOMIAO/deep-learning-for-image-processing#779]
Traceback (most recent call last):
  File "D:\software\Python\project\faster_rcnn\predict-dianchi.py", line 152, in <module>
    main()
  File "D:\software\Python\project\faster_rcnn\predict-dianchi.py", line 103, in main
    plot_img = draw_objs(original_img,
  File "D:\software\Python\project\faster_rcnn\draw_box_utils.py", line 146, in draw_objs
    draw.line([(left, top), (left, bottom), (right, bottom),
  File "D:\software\Anaconda\envs\pytorch\lib\site-packages\PIL\ImageDraw.py", line 172, in line
    ink = self._getink(fill)[0]
  File "D:\software\Anaconda\envs\pytorch\lib\site-packages\PIL\ImageDraw.py", line 130, in _getink
    ink = self.draw.draw_ink(ink)
TypeError: color must be int or single-element tuple

**Comment by WZMIAOMIAO** [comment]
尝试将Pillow更新到最新版本试试
