### ISSUE TITLE
labels.append(self.class_dict[obj["name"]]) KeyError: 'rats ' 

### ISSUE THREAD

**Issue by LY06-10** [WZMIAOMIAO/deep-learning-for-image-processing#833]
博主大大你好，我在使用fasterrcnn训练自己的数据集时出现了这个错误，请问改如何解决：
Traceback (most recent call last):
  File "D:/PROJECT/faster_rcnn/train_res50_fpn.py", line 231, in <module>
    main(args)
  File "D:/PROJECT/faster_rcnn/train_res50_fpn.py", line 144, in main
    scaler=scaler)
  File "D:\PROJECT\faster_rcnn\train_utils\train_eval_utils.py", line 27, in train_one_epoch
    for i, [images, targets] in enumerate(metric_logger.log_every(data_loader, print_freq, header)):
  File "D:\PROJECT\faster_rcnn\train_utils\distributed_utils.py", line 204, in log_every
    for obj in iterable:
  File "D:\Anconda\envs\fasterrcnn\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "D:\Anconda\envs\fasterrcnn\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Anconda\envs\fasterrcnn\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anconda\envs\fasterrcnn\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\PROJECT\faster_rcnn\my_dataset.py", line 91, in __getitem__
    labels.append(self.class_dict[obj["name"]])
KeyError: 'rats '

**Comment by hugyan** [comment]
请问您解决了吗，我也是这种情况

**Comment by Summmerlpc** [comment]
我解决了，我的数据集是从yolo格式转的voc，xml文件中<object>的<name>中没有标签名称，只有数字0,1，把pascal_vol_class.json中的car，person改成对应的0,1就可以
